---
name: "CI: markdown-link-check"
on:
  push:
    branches: [main]
  schedule:
    # 00:00 on Saturday
    - cron: "0 0 * * 6"
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
